# Generated by Django 5.1.3 on 2024-12-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdvBoard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
