# Generated by Django 5.1.3 on 2024-12-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdvBoard', '0002_advertisement_completed_advertisement_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
